### ISSUE TITLE
Improve the API to use WebSockets

### ISSUE THREAD

**Issue by phil-lgr** [dabana/movehome#13]
_From @dabana on August 3, 2017 17:30_

Desired behavior of the app:

Lightning tab: two buttons, one for the kitchen, one for the bathroom.

Light buttons become yellow when light button is PRESSED and RELEASED. The button stays yellow to show the light is ON. To close the light the button is PRESSED and RELEASED. The button goes back to white and the light turns OFF.

Movement tab:

Arrow buttons become grey when PRESSED. When PRESSED, a request is sent to START the motor. The motor STAYS ON until the button is RELEASED. When the button is RELEASED, it becomes white and the motor STOPS. When both buttons are pressed at the same time, the motor stops (I things this is already taken care of in the PLC logic, I have to double check with Jim)

_Copied from original issue: phil-lgr/movehome#21_

**Comment by phil-lgr** [comment]
_From @dabana on August 3, 2017 17:53_

End-points of the API:

- Kitchen light ON: runs GPIO.output([gpio#], 1)
- Kitchen light OFF: runs GPIO.output([gpio#], 0)
- Bathroom light ON: runs GPIO.output([gpio#], 1)
- Bathroom light OFF: runs GPIO.output([gpio#], 0)
- Motor left ON: runs GPIO.output([gpio#], 1)
- Motor right ON: runs GPIO.output([gpio#], 1)
- Motor left OFF: runs GPIO.output([gpio#], 0)
- Motor right OFF: runs GPIO.output([gpio#], 0)

**Comment by phil-lgr** [comment]
_From @dabana on August 6, 2017 20:20_

Websocket ([Django channels](https://blog.heroku.com/in_deep_with_django_channels_the_future_of_real_time_apps_in_django)) pour le moteur avec des EVENTS à toutes 100 ms

Http pour la lumière

**Comment by phil-lgr** [comment]
_From @dabana on August 7, 2017 12:43_

Options for Websocket support over a Python web server:

- [Django channels](https://blog.heroku.com/in_deep_with_django_channels_the_future_of_real_time_apps_in_django) : fairly new and beta. Unable to install so far.

- [Tornado](http://www.tornadoweb.org/en/stable/) : Totally different framework then Django. Need to start from scratch...

- [Twisted](https://github.com/twisted/twisted/tree/websocket-4173-4) can be used on top of django using this [very thorough tutorial](https://ferretfarmer.net/2013/09/05/tutorial-real-time-chat-with-django-twisted-and-websockets-part-2/). Twisted has been there for a while and is well supported. But it is harder to get started with.

- [gevent](https://ferretfarmer.net/2013/09/05/tutorial-real-time-chat-with-django-twisted-and-websockets-part-2/) provides asyncchronous execution using greenlets. It is said to be a lot more simple and transparent. A [Getting started guide](http://www.pixeldonor.com/2014/jan/10/django-gevent-and-socketio/) is available but  I can't get through the installing stage...

**Comment by phil-lgr** [comment]
_From @dabana on August 7, 2017 14:50_

root@7e8616773b10:/# sudo pip3 install channels
Downloading/unpacking channels
  Downloading channels-1.1.6-py2.py3-none-any.whl (56kB): 56kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2595, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2457, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2401, in requires
    dm = self._dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2597, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2621, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2686, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'asgiref ~=1.1', 'at', ' ~=1.1')

Storing debug log for failure in /root/.pip/pip.log

**Comment by phil-lgr** [comment]
_From @dabana on August 7, 2017 15:12_

same error outisde docker

**Comment by phil-lgr** [comment]
_From @dabana on August 7, 2017 15:14_

root@7e8616773b10:/# sudo pip install -U channels
Downloading/unpacking channels
  Downloading channels-1.1.6-py2.py3-none-any.whl (56kB): 56kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2401, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2597, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2621, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 49, in <lambda>
    next = lambda o: o.next()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2686, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'asgiref ~=1.1', 'at', ' ~=1.1')

Storing debug log for failure in /root/.pip/pip.log

**Comment by phil-lgr** [comment]
_From @dabana on August 7, 2017 20:54_

```
sudo pip3 install -vU setuptools
sudo pip3 install -U channels
```

get the error:

```
distutils.errors.DistutilsError: Could not find suitable distrbituion for Requirement.parce('incremental>16.10.1')

**Comment by phil-lgr** [comment]
_From @dabana on August 7, 2017 21:27_

While installing on docker I got the message:

```
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-_tuqlyfb/twisted/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-b3ah1f_4-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-_tuqlyfb/twisted
Storing debug log for failure in /root/.pip/pip.log

```

Can't tell if it is installed correctly or not but the myserver app loads normally on the movehome automated build made from the new image (0.0.7).

**Comment by phil-lgr** [comment]
_From @dabana on August 8, 2017 12:51_

Tested the very first part of the django server tutorials (HelloWorld) add got this error while starting server as expeted, django channels is not installed properly...

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x75cda6f0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/usr/local/lib/python3.4/dist-packages/channels/apps.py", line 17, in ready
    monkeypatch_django()
  File "/usr/local/lib/python3.4/dist-packages/channels/hacks.py", line 10, in monkeypatch_django
    from .management.commands.runserver import Command as RunserverCommand
  File "/usr/local/lib/python3.4/dist-packages/channels/management/commands/runserver.py", line 5, in <module>
    from daphne.server import Server, build_endpoint_description_strings
  File "/usr/local/lib/python3.4/dist-packages/daphne/server.py", line 8, in <module>
    from twisted.internet import reactor, defer
ImportError: No module named 'twisted.internet'
```

**Comment by phil-lgr** [comment]
_From @dabana on August 8, 2017 13:1_

Tried running outside the docker container direcctly on the Pi. Got the error messages:

```
Performing system checks...

System check identified no issues (0 silenced).
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x758c1738>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/sqlite3/base.py", line 198, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/channels/management/commands/runserver.py", line 55, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 422, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/sqlite3/base.py", line 198, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
```

**Comment by phil-lgr** [comment]
_From @dabana on August 8, 2017 14:49_

Trying a fresh install using [this guide](https://artandlogic.com/2016/06/django-channels-ground-part-1/) both on docker and directly on the Pi.

**Comment by phil-lgr** [comment]
_From @dabana on August 8, 2017 15:53_

Got this error while installing package inside a docker container. This does not happen direclty on the Pi.

```
unable to execute 'arm-linux-gnueabihf-gcc': No such file or directory

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /home/root/venv/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-KgYrEs/Twisted/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Nt_zCV-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/root/venv/include/site/python2.7 failed with error code 1 in /tmp/pip-build-KgYrEs/Twisted
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by phil-lgr** [comment]
_From @dabana on August 8, 2017 16:57_

Finally made the first step of the tutorial work on the Pi. I will try inside docker...

![image](https://user-images.githubusercontent.com/29574757/29084122-07e99332-7c39-11e7-9670-da204cbb84d0.png)

**Comment by phil-lgr** [comment]
_From @dabana on August 8, 2017 17:6_

Just can't make it work inside a docker container ...

```
root@a67f1d470b56:~/movehome/DjangoTutorials/myproject# sudo python manage.py runserver 192.168.0.170:8000
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
root@a67f1d470b56:~/movehome/DjangoTutorials/myproject# sudo python3 manage.
py runserver 192.168.0.170:8000
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x75e81f60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.4/dist-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'channels'
```

**Comment by phil-lgr** [comment]
_From @dabana on August 8, 2017 21:58_

Got to the point where we want to switch to a Redis back-end in the tutorial instead of a asgiref.inmemory. 

- Tried running the server once, did not work.
- Did ``` pip install asgi-redis ```, did not work
- Did ``` pip3 install asgi-redis ```, and server sends out error 111 constistently after runnin runserver
- Changed the port to 8000 and error 111 comes in again

All this was done outside docker on the raspberry pi

**Comment by dabana** [comment]
BackNet project suspended
